server:
  port: 9002

spring:
  application:
    name: api-service2

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9004/eureka/
  instance:
    prefer-ip-address: false
