server:
  port: 9003

spring:
  application:
    name: api-service3

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9004/eureka/
  instance:
    prefer-ip-address: false

#logs
logging:
  level:
    com: debug
    org: error
